apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # https://github.com/cloudnative-pg/plugin-barman-cloud/tags
  - https://github.com/cloudnative-pg/plugin-barman-cloud/releases/download/v0.3.0/manifest.yaml

patches:
  - target:
      kind: ".*"
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: cnpg-operator
