apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: connector-configuration-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["cnpg-cluster-admin"]
    verbs: ["get"]
