apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - connectors
  - kafka.yaml
  - kafka-connect.yaml
  - kafka-node-pool.yaml
  - cluster-role.yaml
  - cluster-role-binding.yaml
  - certificate.yaml
