apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kafka-sasl-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: password-64-length
      rewrite:
        - regexp:
            source: ^password$
            target: client-password-1
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: password-64-length
      rewrite:
        - regexp:
            source: ^password$
            target: client-password-2
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: password-64-length
      rewrite:
        - regexp:
            source: ^password$
            target: inter-broker-password
  refreshPolicy: OnChange
  target:
    name: kafka-sasl-secret
    template:
      type: Opaque
      engineVersion: v2
      metadata:
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
          reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
          reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "kafka-ui"
          reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "kafka-ui"
      data:
        client-passwords: '{{ index . "client-password-1" }},{{ index . "client-password-2" }}'
        client-password-1: '{{ index . "client-password-1" }}'
        client-password-2: '{{ index . "client-password-2" }}'
        inter-broker-password: '{{ index . "inter-broker-password" }}'
