packages:
  - apps/*
  - databases/*
  - packages/*
  - tooling/*
catalog:
  eslint: ^9.28.0
  prettier: ^3.5.3
  tailwindcss: ^3.4.15
  typescript: ^5.8.3
  zod: ^3.25.49
  dotenv-cli: ^8.0.0
  "@tanstack/react-query": ^5.80.7
  "@trpc/client": ^11.4.0
  "@trpc/tanstack-react-query": ^11.4.0
  "@trpc/server": ^11.4.0,
  "@t3-oss/env-core": ^0.13.8
catalogs:
  react19:
    react: 19.1.0
    react-dom: 19.1.0
    "@types/react": ^19.1.6
    "@types/react-dom": ^19.1.5
onlyBuiltDependencies:
  - bufferutil
  - core-js-pure
  - esbuild
  - sharp
  - utf-8-validate
