apiVersion: v1
kind: Secret
metadata:
  name: repo-monorepo-template
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    managed-by: argocd.argoproj.io
type: Opaque
stringData:
  type: git
  name: monorepo-template
  url: file:///mnt/monorepo-template.git
