apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - repo: https://emberstack.github.io/helm-charts
    name: reflector
    # https://artifacthub.io/packages/helm/emberstack/reflector
    # issue with the latest version: https://github.com/emberstack/kubernetes-reflector/issues/486#issuecomment-2761795987
    version: 7.1.288
    releaseName: reflector
    namespace: reflector
