apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - temporal-httproute.yaml

patches:
  - target:
      kind: Deployment
      name: temporal-ui
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env
        value:
          - name: TEMPORAL_ADDRESS
            value: "temporal:7233"
          - name: TEMPORAL_CORS_ORIGINS
            value: "https://temporal.127.0.0.1.nip.io"

