apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-ui
spec:
  template:
    spec:
      containers:
        - name: temporal-ui
          env:
            - name: TEMPORAL_CSRF_COOKIE_INSECURE
              value: "true"
