apiVersion: v1
kind: Secret
metadata:
  name: repo-voltade-os
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    managed-by: argocd.argoproj.io
type: Opaque
stringData:
  type: git
  name: voltade-os
  url: "${repo_url}"
  username: "${repo_username}"
  password: "${repo_password}"
