apiVersion: v1
kind: Secret
metadata:
  name: repo-helm-oci
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    managed-by: argocd.argoproj.io
type: Opaque
# https://docs.aws.amazon.com/AmazonECR/latest/userguide/push-oci-artifact.html
# https://helm.sh/docs/topics/registries/
stringData:
  type: helm
  name: helm-oci
  url: "${oci_url}"
  enableOCI: "true"
  username: "${oci_username}"
  password: "${oci_password}"
