apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: all-apps
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    # https://argo-cd.readthedocs.io/en/stable/user-guide/auto_sync/
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: "${repo_url}"
    targetRevision: HEAD
    path: "${appsets_path}"
    directory:
      include: "${appsets_include}"
