apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - httproute.yaml

helmCharts:
  - name: kafka-ui
    namespace: kafka-ui
    releaseName: kafka-ui
    repo: https://kafbat.github.io/helm-charts
    valuesInline:
      yamlApplicationConfig:
        kafka:
          clusters:
            - name: kafka-cluster
              bootstrapServers: kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
              kafkaConnect:
                - name: kafka-connect-cluster
                  address: http://kafka-connect-cluster-connect-api.kafka.svc.cluster.local:8083

      # Service configuration
      service:
        type: ClusterIP
        port: 8080

      # Resource limits
      resources:
        limits:
          cpu: 200m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 256Mi
