apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - httproute.yaml

helmCharts:
  - name: kafka-ui
    namespace: kafka-ui
    releaseName: kafka-ui
    repo: https://kafbat.github.io/helm-charts
    valuesInline:
      # Configure via env instead of configmap to source secret password
      envs:
        secretMappings:
          ADMIN_PASSWORD:
            name: kafka-sasl-secret
            keyName: client-password-1

      env:
        KAFKA_CLUSTERS_0_NAME: dev-kafka
        KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka.kafka.svc.cluster.local:9092
        KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_PLAINTEXT
        KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: SCRAM-SHA-512
        KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="admin" password="$(ADMIN_PASSWORD)";'

      # Service configuration
      service:
        type: ClusterIP
        port: 8080

      # Resource limits
      resources:
        limits:
          cpu: 200m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 256Mi
