apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - httproute.yaml

helmCharts:
  - name: kafka-ui
    namespace: kafka-ui
    releaseName: kafka-ui
    repo: https://kafbat.github.io/helm-charts
    valuesInline:
      yamlApplicationConfig:
        kafka:
          clusters:
            - name: dev-kafka
              bootstrapServers: kafka.kafka.svc.cluster.local:9092
              properties:
                security.protocol: PLAINTEXT
                # Timeout settings for better debugging
                metadata.max.age.ms: 10000
                request.timeout.ms: 30000
                connections.max.idle.ms: 300000
        auth:
          type: disabled
        management:
          health:
            ldap:
              enabled: false
        # Enable debug logging for troubleshooting
        logging:
          level:
            root: DEBUG
            com.provectus.kafka.ui: DEBUG

      # Service configuration
      service:
        type: ClusterIP
        port: 8080

      # Resource limits
      resources:
        limits:
          cpu: 200m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 256Mi
